.\" Copyright (c) 1994 Peter Tobias (tobias@server.et-inf.fho-emden.de),
.\" This file may be distributed under the GNU General Public License.
.\"
.\" $Id: ftpusers.5,v 1.11 2000/07/30 23:56:57 dholland Exp $
.\"
.Dd April 22, 1994
.Dt FTPUSERS 5
.Os "Linux NetKit (0.17)"
.Sh NAME
.Nm ftpusers
.Nd file which lists users who are not allowed to use ftp
.Sh DESCRIPTION
.Pa /etc/ftpusers
is used by
.Xr ftpd 8 ;
the file contains a list of users who are not allowed to use the
ftp command. For security reasons at least users like ``root'', ``bin'',
``uucp'' and ``news'' should be listed in this file. 
Blank lines and lines beginning with `#' are ignored.
.Pp
Note: a lines with `#' in the
.Em middle
is 
.Em not
a comment. Don't put `#' after a name to comment it; use another line,
or things will silently fail on you.
.Sh EXAMPLES
.Pa /etc/ftpusers
might contain the following entries:
.Bd -literal
#
# /etc/ftpusers
#
root
uucp
news
.Ed
.Sh FILES
.Pa /etc/ftpusers
.Sh SEE ALSO
.Xr ftp 1 ,
.Xr ftpd 8
