.\" "%W% %G%"
.TH FTPCK 1
.SH NAME
ftpck \- WU\-FTPD Configuration Checker
.SH SYNOPSIS
.B ftpck
[ -ceFghprstuvx ] [-f accessfile]
.SH DESCRIPTION
.I ftpck
is a utility to verify the various files required to run the WU-FTPD ftp
server. This utility is meant to be run after you make changes to your
WU-FTPD configuration files.
.P
ftpck is intended to check all fields in the WU-FPTD files
to assure proper syntax. It checks to assure that all files
referenced in the various wu-ftpd system files exist. It checks
modes on files as well as modes on ftp directories specified.
.P
The following WU-FTPD configuration files being tested.
.IP
ftpaccess, ftpconversions, ftphosts, ftppidnames, ftpgroups, ftpservers, ftpusers, xferlogs
.P
Additionally, the _PATH_EXECPATH define, is checked as is the
inetd.conf file.
.P
With no options, all WU-FTPD configuration files are checked.  More than 
one set of checks can be specified at a time.
.SH OPTIONS
.TP
.I \-a
Verify aliases and cdpaths listed are usable for anonymous/virtual ftp users.
.TP
.I \-c
Check ftpconversions file defined as _PATH_CVT.
.TP
.I \-d
Turn on describe mode. (Very verbose). A second -d enables accessfile 
line display.
.TP
.I \-e
Check _PATH_EXECPATH not == /bin or other system command directories
that might open up a large security hole on your system.
.TP
.I \-f 
Check ftpaccess file defined as _PATH_FTPACCESS.
.TP
.I \-g
Check ftpgroups file defined as _PATH_PRIVATE.
.TP
.I \-h
Check ftphosts file defined as _PATH_FTPHOSTS.
.TP
.I \-i
Check inetd.conf file at /etc/inetd.conf.
.TP
.I \-p
Check pid directory defined by _PATH_PIDNAMES.
.TP
.I \-r
Verify aliases and cdpaths listed are usable by real system users.
.TP
.I \-s
Check ftpservers file defined as _PATH_FTPSERVERS. This file is not
used if you are not supporting "Complete Virtual Hosting."
.TP
.I \-u
Check ftpusers file defined as _PATH_FTPUSERS. 
.TP
.I \-v
Produce verbose output.
.TP
.I \-x
Check xferlog file defined as _PATH_XFERLOG.
.TP
.I \-C " conversions"
Check specified ftpconversions file
.TP
.I \-F " ftpaccess"
Check the specified ftpaccess file
.TP
.I \-G " ftpgroups"
Check the specified ftpgroups file
.TP
.I \-H " ftphosts"
Check the specified ftphosts file
.TP
.I \-I " inetd.conf"
Check the specified inetd.conf file
.TP
.I \-S " ftpservers"
Check the specified ftpservers file
.TP
.I \-U " ftpusers"
Check the specified ftpusers file
.TP
.I \-?
Display a simple help usage message.
.SH "CREDITS"
Thanks! to the following people for helping me improve ftpck. From
bug fixes to great ideas, these people made it better.
.P
Jim Tollefson <jimt@statsci.com>
.br
C. Paul Ferroni" <Paul.Ferroni@ab.com> 
.br
bobh@hal.com (Bob Hardy)
.br
Bob Luckin <bobl@dadd.ti.com>
.br
Emil Isberg <emil.isberg@mds.mdh.se>
.br
Jason Spears <jspears@usit.net>
.br
john@galton.ucl.ac.uk (John Attwood)
.br
Perry Rovers <perry@Garfield.IAEhv.nl>
.br
Serge ALGAROTTI <Serge.Algarotti@cemef.cma.fr>
.br
rah@lynxhub.ho.att.com (Roger A. Hanke)
.SH "SEE ALSO"
ftpaccess(5), xferlog(5), ftpconversions(5), ftpshut(8), ftpd(8)
.SH BUGS
None known.
.SH ADDITIONAL INFORMATION
http://www.landfield.com/wu-ftpd/ftpck/
