.\" SCCSID: @(#)$Id: ftphosts.5,v 1.5 1998/07/06 08:59:31 sob BETA-18 $
.\" based on ftphosts.5 1.2 1/26/93
.\" 
.TH ftphosts 5 
.SH Name
ftphosts \- ftpd individual user host access file
.SH Description
The ftphosts file is used to allow or deny access to certain
accounts from various hosts.
.SH Access Capabilities
.TP 0.5i
.B allow <username> <addrglob> [<addrglob> ...]
Only allow host(s) matching <addrglob> to log in as <username>.
.TP 0.5i
.B deny <username> <addrglob> [<addrglob> ...]
Always deny host(s) matching <addrglob> to log in as <username>.
.PP
To regulate anonymous ftp access, use the username
.B ftp
in this file. The username
.B anonymous
will be ignored.
.PP
The <addrglob> may be also be specified as address/cidr or address:netmask.  For example:
10.0.0.0/8 or 10.0.0.0:255.0.0.0
.SH Files
FTPLIB/ftphosts
.SH See Also
.BR ftpd(8) ,
.BR ftpaccess(5) ,
.BR ftplog(5) ,
.BR ftpconversions(5) ,
.BR ftpshut(8)
