.\" @(#)$Id: xferlog.5,v 1.1.1.1 1998/08/21 18:10:29 root Exp $
.TH XFERLOG 5
.SH NAME
xferlog \- FTP server logfile
.SH DESCRIPTION
.LP
The
.B xferlog
file contains logging information from the FTP server daemon,
.BR ftpd (8).
This file usually is found in /usr/adm, but can be located anywhere by using a
option to
.BR ftpd (8).
Each server entry is composed of a single line of the following form, 
with all fields being separated by spaces.
.IP
.I
current-time\ \  transfer-time\ \  remote-host\ \  file-size\ \  filename\ \  transfer-type\ \  special-action-flag\ \  direction\ \  access-mode\ \  username\ \  service-name\ \  authentication-method\ \  authenticated-user-id\ \  completion-status
.LP
.TP 20
.I current-time
is the current local time in the form "DDD MMM dd hh:mm:ss YYYY". Where DDD
is the day of the week, MMM is the month, dd is the day of the month,
hh is the hour, mm is the minutes, ss is the seconds, and YYYY is the year.
.TP 
.I transfer-time
is the total time in seconds for the transfer.
.TP
.I remote-host
is the remote host name.
.TP
.I file-size
is the size of the transferred file in bytes.
.TP
.I filename
is the name of the transferred file.
.TP
.I transfer-type
is a single character indicating the type of transfer. Can be one of:
.RS
.RS
.PD 0
.TP 10
.B a
for an ascii transfer
.TP
.B b
for a binary transfer
.PD
.RE
.RE
.TP
.I special-action-flag
is one or more single character flags indicating any special action taken. 
Can be one or more of: 
.RS
.RS
.PD 0
.TP 10
.B C
file was compressed
.TP
.B U
file was uncompressed
.TP
.B T
file was tar'ed
.TP
.B _
no action was taken
.PD
.RE
.RE
.TP
.I direction
is the direction of the transfer. Can be one of:
.RS
.RS
.PD 0
.TP 10
.B o
outgoing
.TP
.B i
incoming
.PD
.RE
.RE
.TP
.I access-mode
is the method by which the user is logged in. Can be one of:
.RS
.RS
.PD 0
.TP 10
.B a
(anonymous) is for an anonymous guest user. 
.TP
.B g
(guest) is for an passworded guest user (see the
.BR guestgroup
command in
.BR ftpaccess(5)
). 
.TP
.B r
(real) is for a local authenticated user.
.PD
.RE
.RE
.TP
.I username
is the local username, or if guest, the ID string given. 
.TP
.I service-name
is the name of the service being invoked, usually FTP.
.TP
.I authentication-method
is the method of authentication used. Can be one of:
.RS
.RS
.PD 0
.TP 10
.B 0
none
.TP
.B 1
RFC931 Authentication
.PD
.RE
.RE
.TP
.I authenticated-user-id
is the user id returned by the authentication method. 
A * is used if an authenticated user id is not available.
.TP
.I completion-status
is a single character indicating the status of the transfer.  Can be one of:
.RS
.RS
.PD 0
.TP 10
.B c
complete transfer
.TP
.B i
incomplete transfer
.PD
.RE
.RE
.SH FILES
.PD 0
.TP 20
.B /usr/adm/xferlog
.SH "SEE ALSO"
.BR ftpd(8),
.BR ftpaccess(5)
